[build]
  command = "npm run build"  # Replace with your build command
  publish = "build"          # Directory where your app is built (default for React)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
